"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.buildCollectionPageSchema = exports.buildFAQSchema = exports.buildArticleSchema = exports.buildBreadcrumbSchema = exports.buildOrganizationSchema = exports.buildArticleKeywords = exports.FREE_CONTENT_KEYWORDS = exports.buildArticleMetadata = exports.buildNoIndexMetadata = exports.buildPageMetadata = exports.absoluteUrl = exports.DEFAULT_OG_IMAGE = exports.DEFAULT_KEYWORDS = exports.DEFAULT_DESCRIPTION = exports.SITE_NAME = exports.SITE_URL = void 0;
var site_1 = require("./site");
Object.defineProperty(exports, "SITE_URL", { enumerable: true, get: function () { return site_1.SITE_URL; } });
Object.defineProperty(exports, "SITE_NAME", { enumerable: true, get: function () { return site_1.SITE_NAME; } });
Object.defineProperty(exports, "DEFAULT_DESCRIPTION", { enumerable: true, get: function () { return site_1.DEFAULT_DESCRIPTION; } });
Object.defineProperty(exports, "DEFAULT_KEYWORDS", { enumerable: true, get: function () { return site_1.DEFAULT_KEYWORDS; } });
Object.defineProperty(exports, "DEFAULT_OG_IMAGE", { enumerable: true, get: function () { return site_1.DEFAULT_OG_IMAGE; } });
Object.defineProperty(exports, "absoluteUrl", { enumerable: true, get: function () { return site_1.absoluteUrl; } });
var metadata_1 = require("./metadata");
Object.defineProperty(exports, "buildPageMetadata", { enumerable: true, get: function () { return metadata_1.buildPageMetadata; } });
Object.defineProperty(exports, "buildNoIndexMetadata", { enumerable: true, get: function () { return metadata_1.buildNoIndexMetadata; } });
Object.defineProperty(exports, "buildArticleMetadata", { enumerable: true, get: function () { return metadata_1.buildArticleMetadata; } });
var keywords_1 = require("./keywords");
Object.defineProperty(exports, "FREE_CONTENT_KEYWORDS", { enumerable: true, get: function () { return keywords_1.FREE_CONTENT_KEYWORDS; } });
Object.defineProperty(exports, "buildArticleKeywords", { enumerable: true, get: function () { return keywords_1.buildArticleKeywords; } });
var schema_1 = require("./schema");
Object.defineProperty(exports, "buildOrganizationSchema", { enumerable: true, get: function () { return schema_1.buildOrganizationSchema; } });
Object.defineProperty(exports, "buildBreadcrumbSchema", { enumerable: true, get: function () { return schema_1.buildBreadcrumbSchema; } });
Object.defineProperty(exports, "buildArticleSchema", { enumerable: true, get: function () { return schema_1.buildArticleSchema; } });
Object.defineProperty(exports, "buildFAQSchema", { enumerable: true, get: function () { return schema_1.buildFAQSchema; } });
Object.defineProperty(exports, "buildCollectionPageSchema", { enumerable: true, get: function () { return schema_1.buildCollectionPageSchema; } });
