/**
 * Central activity / audit event action vocabulary.
 * Add new actions here — UI filters and logs consume these strings.
 */
export const ActivityActions = {
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGIN: 'USER_LOGIN',
  USER_COMPLETED_MODULE: 'USER_COMPLETED_MODULE',
  USER_COMPLETED_LESSON: 'USER_COMPLETED_LESSON',
  USER_COMPLETED_TRB: 'USER_COMPLETED_TRB',
  USER_FLASHCARD_SESSION: 'USER_FLASHCARD_SESSION',
  COMMUNITY_POST_CREATED: 'COMMUNITY_POST_CREATED',

  CONTENT_CREATED: 'CONTENT_CREATED',
  CONTENT_UPDATED: 'CONTENT_UPDATED',
  CONTENT_PUBLISHED: 'CONTENT_PUBLISHED',
  CONTENT_UNPUBLISHED: 'CONTENT_UNPUBLISHED',
  CONTENT_SUBMITTED_REVIEW: 'CONTENT_SUBMITTED_REVIEW',
  CONTENT_APPROVED: 'CONTENT_APPROVED',
  CONTENT_DELETED: 'CONTENT_DELETED',

  MODULE_CREATED: 'MODULE_CREATED',
  MODULE_UPDATED: 'MODULE_UPDATED',
  MODULE_DELETED: 'MODULE_DELETED',

  ADMIN_LOGIN: 'ADMIN_LOGIN',
  ADMIN_ROLE_CHANGED: 'ADMIN_ROLE_CHANGED',
  ADMIN_SETTINGS_CHANGED: 'ADMIN_SETTINGS_CHANGED',
  ADMIN_USER_UPDATED: 'ADMIN_USER_UPDATED',

  SECURITY_PERMISSION_DENIED: 'SECURITY_PERMISSION_DENIED',
  SECURITY_FAILED_LOGIN: 'SECURITY_FAILED_LOGIN',
  SECURITY_API_ERROR: 'SECURITY_API_ERROR',
} as const;

export type ActivityAction = (typeof ActivityActions)[keyof typeof ActivityActions];

export const SECURITY_ACTIONS = new Set<string>([
  ActivityActions.ADMIN_LOGIN,
  ActivityActions.ADMIN_ROLE_CHANGED,
  ActivityActions.ADMIN_SETTINGS_CHANGED,
  ActivityActions.SECURITY_PERMISSION_DENIED,
  ActivityActions.SECURITY_FAILED_LOGIN,
  ActivityActions.SECURITY_API_ERROR,
]);

export const ADMIN_ACTIONS = new Set<string>([
  ActivityActions.ADMIN_LOGIN,
  ActivityActions.ADMIN_ROLE_CHANGED,
  ActivityActions.ADMIN_SETTINGS_CHANGED,
  ActivityActions.ADMIN_USER_UPDATED,
  ActivityActions.CONTENT_DELETED,
  ActivityActions.MODULE_DELETED,
  ActivityActions.CONTENT_PUBLISHED,
  ActivityActions.CONTENT_APPROVED,
]);
